In [1]:
import requests
import json
import uuid
from IPython.display import display_javascript, display_html, display
import pandas as pd

response = requests.get("http://api.openweathermap.org/data/2.5/forecast?id=5780993&APPID=e0c55e00bf021f6142de334823046e9e&units=imperial")
weather = response.content.decode("utf-8")
weatherDict = json.loads(weather)

In [2]:
print(json.dumps(weatherDict, indent=2))

{
  "city": {
    "sys": {
      "population": 0
    },
    "name": "Salt Lake City",
    "population": 0,
    "coord": {
      "lon": -111.891052,
      "lat": 40.76078
    },
    "id": 5780993,
    "country": "US"
  },
  "message": 0.1881,
  "list": [
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 50.97,
        "pressure": 872.29,
        "temp_kf": 3.65,
        "grnd_level": 872.29,
        "sea_level": 1033.97,
        "temp": 57.54,
        "temp_max": 57.54,
        "humidity": 96
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-05 18:00:00",
      "dt": 1478368800,
      "wind": {
        "speed": 3.56,
        "deg": 174.509
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 54.21,
        "pressure": 870.35,
        "temp_kf": 2.74,
        "grnd_level": 870.35,
        "sea_level": 1030.27,
        "temp": 59.14,
        "temp_max": 59.14,
        "humidity": 89
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-05 21:00:00",
      "dt": 1478379600,
      "wind": {
        "speed": 4.54,
        "deg": 320.501
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 50.68,
        "pressure": 869.23,
        "temp_kf": 1.82,
        "grnd_level": 869.23,
        "sea_level": 1029.89,
        "temp": 53.96,
        "temp_max": 53.96,
        "humidity": 94
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 00:00:00",
      "dt": 1478390400,
      "wind": {
        "speed": 3.09,
        "deg": 343.505
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 43.65,
        "pressure": 868.77,
        "temp_kf": 0.91,
        "grnd_level": 868.77,
        "sea_level": 1031.72,
        "temp": 45.28,
        "temp_max": 45.28,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 03:00:00",
      "dt": 1478401200,
      "wind": {
        "speed": 2.33,
        "deg": 64.5009
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 42.16,
        "pressure": 868.33,
        "temp_kf": 0,
        "grnd_level": 868.33,
        "sea_level": 1032.49,
        "temp": 42.16,
        "temp_max": 42.16,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 06:00:00",
      "dt": 1478412000,
      "wind": {
        "speed": 2.71,
        "deg": 132.002
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 41.08,
        "pressure": 867.89,
        "temp_kf": 0,
        "grnd_level": 867.89,
        "sea_level": 1032.81,
        "temp": 41.08,
        "temp_max": 41.08,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 09:00:00",
      "dt": 1478422800,
      "wind": {
        "speed": 2.08,
        "deg": 198.502
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 39.91,
        "pressure": 867.67,
        "temp_kf": 0,
        "grnd_level": 867.67,
        "sea_level": 1033.09,
        "temp": 39.91,
        "temp_max": 39.91,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 12:00:00",
      "dt": 1478433600,
      "wind": {
        "speed": 3.38,
        "deg": 157
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 40.72,
        "pressure": 868.24,
        "temp_kf": 0,
        "grnd_level": 868.24,
        "sea_level": 1033.76,
        "temp": 40.72,
        "temp_max": 40.72,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 15:00:00",
      "dt": 1478444400,
      "wind": {
        "speed": 4.83,
        "deg": 157.004
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 52.57,
        "pressure": 869.48,
        "temp_kf": 0,
        "grnd_level": 869.48,
        "sea_level": 1031.05,
        "temp": 52.57,
        "temp_max": 52.57,
        "humidity": 95
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 18:00:00",
      "dt": 1478455200,
      "wind": {
        "speed": 4.16,
        "deg": 276.002
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 52.84,
        "pressure": 870.24,
        "temp_kf": 0,
        "grnd_level": 870.24,
        "sea_level": 1030.37,
        "temp": 52.84,
        "temp_max": 52.84,
        "humidity": 96
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-06 21:00:00",
      "dt": 1478466000,
      "wind": {
        "speed": 4.5,
        "deg": 316.502
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 50.1,
        "pressure": 870.59,
        "temp_kf": 0,
        "grnd_level": 870.59,
        "sea_level": 1031.8,
        "temp": 50.1,
        "temp_max": 50.1,
        "humidity": 99
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-07 00:00:00",
      "dt": 1478476800,
      "wind": {
        "speed": 1.95,
        "deg": 300
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 42.35,
        "pressure": 871.81,
        "temp_kf": 0,
        "grnd_level": 871.81,
        "sea_level": 1035.91,
        "temp": 42.35,
        "temp_max": 42.35,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-07 03:00:00",
      "dt": 1478487600,
      "wind": {
        "speed": 1.59,
        "deg": 345.501
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 39.86,
        "pressure": 873.25,
        "temp_kf": 0,
        "grnd_level": 873.25,
        "sea_level": 1038.83,
        "temp": 39.86,
        "temp_max": 39.86,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-07 06:00:00",
      "dt": 1478498400,
      "wind": {
        "speed": 2.75,
        "deg": 75.0047
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 38.76,
        "pressure": 873.43,
        "temp_kf": 0,
        "grnd_level": 873.43,
        "sea_level": 1039.9,
        "temp": 38.76,
        "temp_max": 38.76,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-07 09:00:00",
      "dt": 1478509200,
      "wind": {
        "speed": 4.41,
        "deg": 123.002
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 37.28,
        "pressure": 874.55,
        "temp_kf": 0,
        "grnd_level": 874.55,
        "sea_level": 1041.85,
        "temp": 37.28,
        "temp_max": 37.28,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-07 12:00:00",
      "dt": 1478520000,
      "wind": {
        "speed": 3.38,
        "deg": 137.003
      }
    },
    {
      "weather": [
        {
          "description": "few clouds",
          "main": "Clouds",
          "icon": "02d",
          "id": 801
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 37.94,
        "pressure": 875.76,
        "temp_kf": 0,
        "grnd_level": 875.76,
        "sea_level": 1043.29,
        "temp": 37.94,
        "temp_max": 37.94,
        "humidity": 100
      },
      "clouds": {
        "all": 12
      },
      "dt_txt": "2016-11-07 15:00:00",
      "dt": 1478530800,
      "wind": {
        "speed": 4.85,
        "deg": 159.001
      }
    },
    {
      "weather": [
        {
          "description": "few clouds",
          "main": "Clouds",
          "icon": "02d",
          "id": 801
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 49.5,
        "pressure": 876.88,
        "temp_kf": 0,
        "grnd_level": 876.88,
        "sea_level": 1040.18,
        "temp": 49.5,
        "temp_max": 49.5,
        "humidity": 98
      },
      "clouds": {
        "all": 12
      },
      "dt_txt": "2016-11-07 18:00:00",
      "dt": 1478541600,
      "wind": {
        "speed": 3.85,
        "deg": 209.502
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 51.91,
        "pressure": 876.45,
        "temp_kf": 0,
        "grnd_level": 876.45,
        "sea_level": 1038.21,
        "temp": 51.91,
        "temp_max": 51.91,
        "humidity": 95
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-07 21:00:00",
      "dt": 1478552400,
      "wind": {
        "speed": 5.08,
        "deg": 315.001
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 48.91,
        "pressure": 876.68,
        "temp_kf": 0,
        "grnd_level": 876.68,
        "sea_level": 1039.33,
        "temp": 48.91,
        "temp_max": 48.91,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 00:00:00",
      "dt": 1478563200,
      "wind": {
        "speed": 3.76,
        "deg": 318.001
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 41.62,
        "pressure": 877.3,
        "temp_kf": 0,
        "grnd_level": 877.3,
        "sea_level": 1042.78,
        "temp": 41.62,
        "temp_max": 41.62,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 03:00:00",
      "dt": 1478574000,
      "wind": {
        "speed": 2.93,
        "deg": 325.502
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 39.24,
        "pressure": 877.56,
        "temp_kf": 0,
        "grnd_level": 877.56,
        "sea_level": 1044.44,
        "temp": 39.24,
        "temp_max": 39.24,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 06:00:00",
      "dt": 1478584800,
      "wind": {
        "speed": 1.03,
        "deg": 216.504
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 37.73,
        "pressure": 877.91,
        "temp_kf": 0,
        "grnd_level": 877.91,
        "sea_level": 1045.54,
        "temp": 37.73,
        "temp_max": 37.73,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 09:00:00",
      "dt": 1478595600,
      "wind": {
        "speed": 2.13,
        "deg": 182.504
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 36.08,
        "pressure": 877.84,
        "temp_kf": 0,
        "grnd_level": 877.84,
        "sea_level": 1046.04,
        "temp": 36.08,
        "temp_max": 36.08,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 12:00:00",
      "dt": 1478606400,
      "wind": {
        "speed": 8.63,
        "deg": 138.009
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 36.95,
        "pressure": 878.49,
        "temp_kf": 0,
        "grnd_level": 878.49,
        "sea_level": 1046.74,
        "temp": 36.95,
        "temp_max": 36.95,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 15:00:00",
      "dt": 1478617200,
      "wind": {
        "speed": 6.2,
        "deg": 152.502
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 46.97,
        "pressure": 878.8,
        "temp_kf": 0,
        "grnd_level": 878.8,
        "sea_level": 1042.44,
        "temp": 46.97,
        "temp_max": 46.97,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 18:00:00",
      "dt": 1478628000,
      "wind": {
        "speed": 3.6,
        "deg": 244.002
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 49.41,
        "pressure": 877.24,
        "temp_kf": 0,
        "grnd_level": 877.24,
        "sea_level": 1038.93,
        "temp": 49.41,
        "temp_max": 49.41,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-08 21:00:00",
      "dt": 1478638800,
      "wind": {
        "speed": 4.41,
        "deg": 321.501
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 46.53,
        "pressure": 876.65,
        "temp_kf": 0,
        "grnd_level": 876.65,
        "sea_level": 1039.16,
        "temp": 46.53,
        "temp_max": 46.53,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-09 00:00:00",
      "dt": 1478649600,
      "wind": {
        "speed": 3.65,
        "deg": 331.501
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 39.59,
        "pressure": 876.82,
        "temp_kf": 0,
        "grnd_level": 876.82,
        "sea_level": 1042.37,
        "temp": 39.59,
        "temp_max": 39.59,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-09 03:00:00",
      "dt": 1478660400,
      "wind": {
        "speed": 2.59,
        "deg": 347.004
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 37.42,
        "pressure": 876.72,
        "temp_kf": 0,
        "grnd_level": 876.72,
        "sea_level": 1043.69,
        "temp": 37.42,
        "temp_max": 37.42,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-09 06:00:00",
      "dt": 1478671200,
      "wind": {
        "speed": 1.34,
        "deg": 298
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "02n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 36.14,
        "pressure": 876.67,
        "temp_kf": 0,
        "grnd_level": 876.67,
        "sea_level": 1044.61,
        "temp": 36.14,
        "temp_max": 36.14,
        "humidity": 100
      },
      "clouds": {
        "all": 8
      },
      "dt_txt": "2016-11-09 09:00:00",
      "dt": 1478682000,
      "wind": {
        "speed": 1.12,
        "deg": 245.502
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01n",
          "id": 800
        }
      ],
      "sys": {
        "pod": "n"
      },
      "main": {
        "temp_min": 36.32,
        "pressure": 876.51,
        "temp_kf": 0,
        "grnd_level": 876.51,
        "sea_level": 1045.14,
        "temp": 36.32,
        "temp_max": 36.32,
        "humidity": 100
      },
      "clouds": {
        "all": 0
      },
      "dt_txt": "2016-11-09 12:00:00",
      "dt": 1478692800,
      "wind": {
        "speed": 5.06,
        "deg": 124.004
      }
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "main": "Clear",
          "icon": "01d",
          "id": 800
        }
      ],
      "sys": {
        "pod": "d"
      },
      "main": {
        "temp_min": 37.39,
        "pressure": 877.02,
        "temp_kf": 0,

In [3]:
# Method for rendering collapsible JSON from: http://stackoverflow.com/questions/18873066/pretty-json-formatting-in-ipython-notebook

class RenderJSON(object):
    def __init__(self, json_data):
        if isinstance(json_data, dict):
            self.json_str = json.dumps(json_data)
        else:
            self.json_str = json
        self.uuid = str(uuid.uuid4())

    def _ipython_display_(self):
        display_html('<div id="{}" style="height: 600px; width:100%;"></div>'.format(self.uuid),
        raw=True)
        
        display_javascript("""
        require(["https://rawgit.com/caldwell/renderjson/master/renderjson.js"], function() {
        document.getElementById('%s').appendChild(renderjson(%s))
        });
        """ % (self.uuid, self.json_str), raw=True)
        
RenderJSON(weatherDict)

In [4]:
#pdWeather = pd.read_json(weatherDict)
#pdWeather

#pd.DataFrame(weatherDict["data"], columns=[x["label"] for x in weatherDict["fields"]])

timeList = []
maxTempList = []
minTempList = []
pressureList = []
humidityList = []
tempList = []
wind_speedList = []
windDegList = []
rainList = []

for weatherEntry in weatherDict["list"]:
    timeList.append(weatherEntry["dt_txt"])
    mainWeather = weatherEntry["main"]
    maxTempList.append(mainWeather["temp_max"])
    minTempList.append(mainWeather["temp_min"])
    pressureList.append(mainWeather["pressure"])
    humidityList.append(mainWeather["humidity"])
    tempList.append(mainWeather["temp"])
    windWeather = weatherEntry["wind"]
    wind_speedList.append(windWeather["speed"])
    windDegList.append(windWeather["deg"])

In [5]:
data = [('DateTime', timeList),
         ('MaxTemp', maxTempList),
         ('MinTemp', minTempList),
         ('Pressure', pressureList),
         ('Humidity', humidityList),
         ('Temperature', tempList),
         ('WindSpeed', wind_speedList), 
         ('WindDeg', windDegList)
         ]
weatherForecast = pd.DataFrame.from_items(data)
weatherForecast

,DateTime,MaxTemp,MinTemp,Pressure,Humidity,Temperature,WindSpeed,WindDeg
0,2016-11-05 18:00:00,57.54,50.97,872.29,96,57.54,3.56,174.5090
1,2016-11-05 21:00:00,59.14,54.21,870.35,89,59.14,4.54,320.5010
2,2016-11-06 00:00:00,53.96,50.68,869.23,94,53.96,3.09,343.5050
3,2016-11-06 03:00:00,45.28,43.65,868.77,100,45.28,2.33,64.5009
4,2016-11-06 06:00:00,42.16,42.16,868.33,100,42.16,2.71,132.0020
5,2016-11-06 09:00:00,41.08,41.08,867.89,100,41.08,2.08,198.5020
6,2016-11-06 12:00:00,39.91,39.91,867.67,100,39.91,3.38,157.0000
7,2016-11-06 15:00:00,40.72,40.72,868.24,100,40.72,4.83,157.0040
8,2016-11-06 18:00:00,52.57,52.57,869.48,95,52.57,4.16,276.0020
9,2016-11-06 21:00:00,52.84,52.84,870.24,96,52.84,4.50,316.5020
10,2016-11-07 00:00:00,50.10,50.10,870.59,99,50.10,1.95,300.0000
11,2016-11-07 03:00:00,42.35,42.35,871.81,100,42.35,1.59,345.5010
12,2016-11-07 06:00:00,39.86,39.86,873.25,100,39.86,2.75,75.0047
13,2016-11-07 09:00:00,38.76,38.76,873.43,100,38.76,4.41,123.0020
14,2016-11-07 12:00:00,37.28,37.28,874.55,100,37.28,3.38,137.0030
15,2016-11-07 15:00:00,37.94,37.94,875.76,100,37.94,4.85,159.0010
16,2016-11-07 18:00:00,49.50,49.50,876.88,98,49.50,3.85,209.5020
17,2016-11-07 21:00:00,51.91,51.91,876.45,95,51.91,5.08,315.0010
18,2016-11-08 00:00:00,48.91,48.91,876.68,100,48.91,3.76,318.0010
19,2016-11-08 03:00:00,41.62,41.62,877.30,100,41.62,2.93,325.5020
20,2016-11-08 06:00:00,39.24,39.24,877.56,100,39.24,1.03,216.5040
21,2016-11-08 09:00:00,37.73,37.73,877.91,100,37.73,2.13,182.5040
22,2016-11-08 12:00:00,36.08,36.08,877.84,100,36.08,8.63,138.0090
23,2016-11-08 15:00:00,36.95,36.95,878.49,100,36.95,6.20,152.5020
24,2016-11-08 18:00:00,46.97,46.97,878.80,100,46.97,3.60,244.0020
25,2016-11-08 21:00:00,49.41,49.41,877.24,100,49.41,4.41,321.5010
26,2016-11-09 00:00:00,46.53,46.53,876.65,100,46.53,3.65,331.5010
27,2016-11-09 03:00:00,39.59,39.59,876.82,100,39.59,2.59,347.0040
28,2016-11-09 06:00:00,37.42,37.42,876.72,100,37.42,1.34,298.0000
29,2016-11-09 09:00:00,36.14,36.14,876.67,100,36.14,1.12,245.5020
30,2016-11-09 12:00:00,36.32,36.32,876.51,100,36.32,5.06,124.0040
31,2016-11-09 15:00:00,37.39,37.39,877.02,100,37.39,7.36,142.0020
32,2016-11-09 18:00:00,47.15,47.15,877.05,100,47.15,3.56,193.5010
33,2016-11-09 21:00:00,49.22,49.22,875.77,100,49.22,5.64,327.5060
34,2016-11-10 00:00:00,46.66,46.66,875.22,100,46.66,3.40,326.5020
35,2016-11-10 03:00:00,39.49,39.49,875.25,100,39.49,4.38,336.0010
36,2016-11-10 06:00:00,37.42,37.42,875.22,100,37.42,4.29,317.0010
37,2016-11-10 09:00:00,40.41,40.41,875.13,100,40.41,2.53,301.0030
38,2016-11-10 12:00:00,40.43,40.43,875.17,100,40.43,1.59,315.0010
39,2016-11-10 15:00:00,39.76,39.76,875.71,100,39.76,1.54,341.0040

In [7]:
weatherForecast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
DateTime       40 non-null object
MaxTemp        40 non-null float64
MinTemp        40 non-null float64
Pressure       40 non-null float64
Humidity       40 non-null int64
Temperature    40 non-null float64
WindSpeed      40 non-null float64
WindDeg        40 non-null float64
dtypes: float64(6), int64(1), object(1)
memory usage: 2.6+ KB

In [8]:
weatherForecast.describe()

,MaxTemp,MinTemp,Pressure,Humidity,Temperature,WindSpeed,WindDeg
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,43.593500,43.183250,874.298500,99.050000,43.593500,3.594500,241.202490
std,6.373733,5.657895,3.423288,2.308846,6.373733,1.646852,88.599292
min,36.080000,36.080000,867.670000,89.000000,36.080000,1.030000,64.500900
25%,38.555000,38.555000,871.505000,100.000000,38.555000,2.480000,157.003000
50%,40.900000,40.900000,875.480000,100.000000,40.900000,3.560000,260.752000
75%,48.987500,48.987500,876.835000,100.000000,48.987500,4.432500,320.751000
max,59.140000,54.210000,878.800000,100.000000,59.140000,8.630000,347.004000