In [1]:
import requests
import json
import uuid
from IPython.display import display_javascript, display_html, display
import pandas as pd

response = requests.get("http://api.openweathermap.org/data/2.5/forecast?id=5780993&APPID=e0c55e00bf021f6142de334823046e9e&units=imperial")
weather = response.content.decode("utf-8")
weatherDict = json.loads(weather)

In [2]:
print(json.dumps(weatherDict, indent=2))

{
  "message": 0.1691,
  "cnt": 40,
  "list": [
    {
      "dt_txt": "2016-11-13 00:00:00",
      "dt": 1478995200,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 325.506,
        "speed": 6.55
      },
      "clouds": {
        "all": 88
      },
      "main": {
        "temp": 55.71,
        "temp_kf": 2.53,
        "pressure": 872.09,
        "sea_level": 1033.54,
        "grnd_level": 872.09,
        "temp_min": 51.15,
        "temp_max": 55.71,
        "humidity": 92
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-13 03:00:00",
      "dt": 1479006000,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 354,
        "speed": 3.6
      },
      "clouds": {
        "all": 36
      },
      "main": {
        "temp": 49.21,
        "temp_kf": 1.9,
        "pressure": 872.52,
        "sea_level": 1036.37,
        "grnd_level": 872.52,
        "temp_min": 45.79,
        "temp_max": 49.21,
        "humidity": 100
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-13 06:00:00",
      "dt": 1479016800,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 142.5,
        "speed": 3.6
      },
      "clouds": {
        "all": 12
      },
      "main": {
        "temp": 45.19,
        "temp_kf": 1.26,
        "pressure": 872.62,
        "sea_level": 1037.89,
        "grnd_level": 872.62,
        "temp_min": 42.92,
        "temp_max": 45.19,
        "humidity": 100
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-13 09:00:00",
      "dt": 1479027600,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 153.501,
        "speed": 5.57
      },
      "clouds": {
        "all": 8
      },
      "main": {
        "temp": 42.51,
        "temp_kf": 0.63,
        "pressure": 872.54,
        "sea_level": 1038.44,
        "grnd_level": 872.54,
        "temp_min": 41.37,
        "temp_max": 42.51,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "02n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-13 12:00:00",
      "dt": 1479038400,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 170.007,
        "speed": 2.04
      },
      "clouds": {
        "all": 56
      },
      "main": {
        "temp": 40.36,
        "temp_kf": 0,
        "pressure": 873.85,
        "sea_level": 1040.51,
        "grnd_level": 873.85,
        "temp_min": 40.36,
        "temp_max": 40.36,
        "humidity": 100
      },
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-13 15:00:00",
      "dt": 1479049200,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 157.501,
        "speed": 4.16
      },
      "clouds": {
        "all": 44
      },
      "main": {
        "temp": 41.42,
        "temp_kf": 0,
        "pressure": 874.45,
        "sea_level": 1041.41,
        "grnd_level": 874.45,
        "temp_min": 41.42,
        "temp_max": 41.42,
        "humidity": 100
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-13 18:00:00",
      "dt": 1479060000,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 169,
        "speed": 3.74
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 50.89,
        "temp_kf": 0,
        "pressure": 875.13,
        "sea_level": 1037.8,
        "grnd_level": 875.13,
        "temp_min": 50.89,
        "temp_max": 50.89,
        "humidity": 92
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-13 21:00:00",
      "dt": 1479070800,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 319.001,
        "speed": 3.85
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 54.33,
        "temp_kf": 0,
        "pressure": 874.58,
        "sea_level": 1035.77,
        "grnd_level": 874.58,
        "temp_min": 54.33,
        "temp_max": 54.33,
        "humidity": 86
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 00:00:00",
      "dt": 1479081600,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 350.508,
        "speed": 2.17
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 50.55,
        "temp_kf": 0,
        "pressure": 874.11,
        "sea_level": 1036.24,
        "grnd_level": 874.11,
        "temp_min": 50.55,
        "temp_max": 50.55,
        "humidity": 90
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 03:00:00",
      "dt": 1479092400,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 100.501,
        "speed": 2.8
      },
      "clouds": {
        "all": 8
      },
      "main": {
        "temp": 44.06,
        "temp_kf": 0,
        "pressure": 874.39,
        "sea_level": 1039.22,
        "grnd_level": 874.39,
        "temp_min": 44.06,
        "temp_max": 44.06,
        "humidity": 98
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "02n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 06:00:00",
      "dt": 1479103200,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 153.504,
        "speed": 7.29
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 42.56,
        "temp_kf": 0,
        "pressure": 874.61,
        "sea_level": 1040.55,
        "grnd_level": 874.61,
        "temp_min": 42.56,
        "temp_max": 42.56,
        "humidity": 99
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 09:00:00",
      "dt": 1479114000,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 140.501,
        "speed": 6.29
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 40.75,
        "temp_kf": 0,
        "pressure": 874.21,
        "sea_level": 1040.62,
        "grnd_level": 874.21,
        "temp_min": 40.75,
        "temp_max": 40.75,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 12:00:00",
      "dt": 1479124800,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 138.503,
        "speed": 7.11
      },
      "clouds": {
        "all": 32
      },
      "main": {
        "temp": 39.91,
        "temp_kf": 0,
        "pressure": 874.17,
        "sea_level": 1040.85,
        "grnd_level": 874.17,
        "temp_min": 39.91,
        "temp_max": 39.91,
        "humidity": 100
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 15:00:00",
      "dt": 1479135600,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 133.504,
        "speed": 7.52
      },
      "clouds": {
        "all": 8
      },
      "main": {
        "temp": 40.04,
        "temp_kf": 0,
        "pressure": 874.72,
        "sea_level": 1041.43,
        "grnd_level": 874.72,
        "temp_min": 40.04,
        "temp_max": 40.04,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "02d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 18:00:00",
      "dt": 1479146400,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 155.001,
        "speed": 4.61
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 50.36,
        "temp_kf": 0,
        "pressure": 874.72,
        "sea_level": 1037.36,
        "grnd_level": 874.72,
        "temp_min": 50.36,
        "temp_max": 50.36,
        "humidity": 91
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-14 21:00:00",
      "dt": 1479157200,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 260.003,
        "speed": 2.08
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 55.01,
        "temp_kf": 0,
        "pressure": 873.36,
        "sea_level": 1034.31,
        "grnd_level": 873.36,
        "temp_min": 55.01,
        "temp_max": 55.01,
        "humidity": 84
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 00:00:00",
      "dt": 1479168000,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 309.004,
        "speed": 2.1
      },
      "clouds": {
        "all": 32
      },
      "main": {
        "temp": 51,
        "temp_kf": 0,
        "pressure": 873.19,
        "sea_level": 1034.73,
        "grnd_level": 873.19,
        "temp_min": 51,
        "temp_max": 51,
        "humidity": 90
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 03:00:00",
      "dt": 1479178800,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 12.5017,
        "speed": 2.1
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 44.23,
        "temp_kf": 0,
        "pressure": 873.37,
        "sea_level": 1037.14,
        "grnd_level": 873.37,
        "temp_min": 44.23,
        "temp_max": 44.23,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 06:00:00",
      "dt": 1479189600,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 73.5031,
        "speed": 2.39
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 41.79,
        "temp_kf": 0,
        "pressure": 873.08,
        "sea_level": 1037.9,
        "grnd_level": 873.08,
        "temp_min": 41.79,
        "temp_max": 41.79,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 09:00:00",
      "dt": 1479200400,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 120.003,
        "speed": 2.93
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 41.4,
        "temp_kf": 0,
        "pressure": 871.95,
        "sea_level": 1037.11,
        "grnd_level": 871.95,
        "temp_min": 41.4,
        "temp_max": 41.4,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 12:00:00",
      "dt": 1479211200,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 153.501,
        "speed": 3.38
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 40.69,
        "temp_kf": 0,
        "pressure": 870.77,
        "sea_level": 1036.27,
        "grnd_level": 870.77,
        "temp_min": 40.69,
        "temp_max": 40.69,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 15:00:00",
      "dt": 1479222000,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 155.003,
        "speed": 3.38
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 40.91,
        "temp_kf": 0,
        "pressure": 869.96,
        "sea_level": 1035.31,
        "grnd_level": 869.96,
        "temp_min": 40.91,
        "temp_max": 40.91,
        "humidity": 100
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 18:00:00",
      "dt": 1479232800,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 240.503,
        "speed": 3.15
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 52.24,
        "temp_kf": 0,
        "pressure": 868.77,
        "sea_level": 1029.98,
        "grnd_level": 868.77,
        "temp_min": 52.24,
        "temp_max": 52.24,
        "humidity": 89
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-15 21:00:00",
      "dt": 1479243600,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 299.001,
        "speed": 1.72
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 55.38,
        "temp_kf": 0,
        "pressure": 865.83,
        "sea_level": 1025.49,
        "grnd_level": 865.83,
        "temp_min": 55.38,
        "temp_max": 55.38,
        "humidity": 85
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 00:00:00",
      "dt": 1479254400,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 304.502,
        "speed": 1.95
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 51.46,
        "temp_kf": 0,
        "pressure": 864.28,
        "sea_level": 1024.77,
        "grnd_level": 864.28,
        "temp_min": 51.46,
        "temp_max": 51.46,
        "humidity": 89
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 03:00:00",
      "dt": 1479265200,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 124,
        "speed": 4.38
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 45.02,
        "temp_kf": 0,
        "pressure": 863.09,
        "sea_level": 1025.81,
        "grnd_level": 863.09,
        "temp_min": 45.02,
        "temp_max": 45.02,
        "humidity": 93
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 06:00:00",
      "dt": 1479276000,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 154.5,
        "speed": 11.23
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 43.45,
        "temp_kf": 0,
        "pressure": 862.29,
        "sea_level": 1025.86,
        "grnd_level": 862.29,
        "temp_min": 43.45,
        "temp_max": 43.45,
        "humidity": 99
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 09:00:00",
      "dt": 1479286800,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 153.005,
        "speed": 14.14
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 44.79,
        "temp_kf": 0,
        "pressure": 860.92,
        "sea_level": 1024.82,
        "grnd_level": 860.92,
        "temp_min": 44.79,
        "temp_max": 44.79,
        "humidity": 95
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 12:00:00",
      "dt": 1479297600,
      "sys": {
        "pod": "n"
      },
      "wind": {
        "deg": 153,
        "speed": 13.22
      },
      "clouds": {
        "all": 0
      },
      "main": {
        "temp": 43.96,
        "temp_kf": 0,
        "pressure": 859.79,
        "sea_level": 1024.05,
        "grnd_level": 859.79,
        "temp_min": 43.96,
        "temp_max": 43.96,
        "humidity": 98
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 15:00:00",
      "dt": 1479308400,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 155.006,
        "speed": 13
      },
      "clouds": {
        "all": 20
      },
      "main": {
        "temp": 44.07,
        "temp_kf": 0,
        "pressure": 858.68,
        "sea_level": 1022.65,
        "grnd_level": 858.68,
        "temp_min": 44.07,
        "temp_max": 44.07,
        "humidity": 97
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 18:00:00",
      "dt": 1479319200,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 194.001,
        "speed": 5.64
      },
      "clouds": {
        "all": 12
      },
      "main": {
        "temp": 50.16,
        "temp_kf": 0,
        "pressure": 858.82,
        "sea_level": 1019.87,
        "grnd_level": 858.82,
        "temp_min": 50.16,
        "temp_max": 50.16,
        "humidity": 89
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ]
    },
    {
      "dt_txt": "2016-11-16 21:00:00",
      "dt": 1479330000,
      "sys": {
        "pod": "d"
      },
      "wind": {
        "deg": 304.001,
        "speed": 12.55
      },
      "rain": {
        "3h": 0.77
      },
      "clouds": {
        "all": 92
      },
      "main": {
        "temp": 44,
        "temp_kf": 0,
        "pressure": 859.43,
        "sea_level": 1019.03,
        "grnd_level": 859.43,
        "temp_min": 44,
        "temp_max": 44,
        "humidity": 100
      },

In [3]:
# Method for rendering collapsible JSON from: http://stackoverflow.com/questions/18873066/pretty-json-formatting-in-ipython-notebook

class RenderJSON(object):
    def __init__(self, json_data):
        if isinstance(json_data, dict):
            self.json_str = json.dumps(json_data)
        else:
            self.json_str = json
        self.uuid = str(uuid.uuid4())

    def _ipython_display_(self):
        display_html('<div id="{}" style="height: 600px; width:100%;"></div>'.format(self.uuid),
        raw=True)
        
        display_javascript("""
        require(["https://rawgit.com/caldwell/renderjson/master/renderjson.js"], function() {
        document.getElementById('%s').appendChild(renderjson(%s))
        });
        """ % (self.uuid, self.json_str), raw=True)
        
RenderJSON(weatherDict)

In [4]:
#pdWeather = pd.read_json(weatherDict)
#pdWeather

#pd.DataFrame(weatherDict["data"], columns=[x["label"] for x in weatherDict["fields"]])

timeList = []
maxTempList = []
minTempList = []
pressureList = []
humidityList = []
tempList = []
wind_speedList = []
windDegList = []
rainList = []

for weatherEntry in weatherDict["list"]:
    timeList.append(weatherEntry["dt_txt"])
    mainWeather = weatherEntry["main"]
    maxTempList.append(mainWeather["temp_max"])
    minTempList.append(mainWeather["temp_min"])
    pressureList.append(mainWeather["pressure"])
    humidityList.append(mainWeather["humidity"])
    tempList.append(mainWeather["temp"])
    windWeather = weatherEntry["wind"]
    wind_speedList.append(windWeather["speed"])
    windDegList.append(windWeather["deg"])

In [40]:
data = [('DateTime', timeList),
         ('MaxTemp', maxTempList),
         ('MinTemp', minTempList),
         ('Pressure', pressureList),
         ('Humidity', humidityList),
         ('Temperature', tempList),
         ('WindSpeed', wind_speedList), 
         ('WindDeg', windDegList)
         ]
weatherForecast = pd.DataFrame.from_items(data)
weatherForecast["DateTime"] = weatherForecast["DateTime"].apply(lambda x: str(x)[:10])

finalForecast = weatherForecast.groupby("DateTime").mean()

finalForecast["MinTemp"] = weatherForecast.groupby("DateTime").min()["MinTemp"]
finalForecast["MaxTemp"] = weatherForecast.groupby("DateTime").max()["MaxTemp"]
finalForecast["MaxPressure"] = weatherForecast.groupby("DateTime").max()["Pressure"]
finalForecast["MinPressure"] = weatherForecast.groupby("DateTime").min()["Pressure"]
finalForecast["MaxWindSpeed"] = weatherForecast.groupby("DateTime").max()["WindSpeed"]
finalForecast["MinWindSpeed"] = weatherForecast.groupby("DateTime").min()["WindSpeed"]

finalForecast

,MaxTemp,MinTemp,Pressure,Humidity,Temperature,WindSpeed,WindDeg,MaxPressure,MinPressure,MaxWindSpeed,MinWindSpeed
DateTime,,,,,,,,,,,
2016-11-13,55.71,40.36,873.47250,96.25,47.45250,4.13875,223.877000,875.13,872.09,6.55,2.04
2016-11-14,55.01,39.91,874.28625,95.25,45.40500,4.98375,179.003125,874.72,873.36,7.52,2.08
2016-11-15,55.38,40.69,870.86500,95.50,45.95500,2.64375,170.377475,873.37,865.83,3.38,1.72
2016-11-16,51.46,43.45,860.91250,95.00,45.86375,9.51375,192.751875,864.28,858.68,14.14,1.95
2016-11-17,39.12,33.52,862.66125,100.00,36.49500,8.48250,275.754750,866.12,859.59,10.11,4.47

In [41]:
finalForecast.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 2016-11-13 to 2016-11-17
Data columns (total 11 columns):
MaxTemp         5 non-null float64
MinTemp         5 non-null float64
Pressure        5 non-null float64
Humidity        5 non-null float64
Temperature     5 non-null float64
WindSpeed       5 non-null float64
WindDeg         5 non-null float64
MaxPressure     5 non-null float64
MinPressure     5 non-null float64
MaxWindSpeed    5 non-null float64
MinWindSpeed    5 non-null float64
dtypes: float64(11)
memory usage: 480.0+ bytes

In [43]:
finalForecast.describe()

,MaxTemp,MinTemp,Pressure,Humidity,Temperature,WindSpeed,WindDeg,MaxPressure,MinPressure,MaxWindSpeed,MinWindSpeed
count,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,51.336000,39.586000,868.43950,96.400000,44.234250,5.952500,208.352845,870.724000,865.910000,8.340000,2.452000
std,7.039711,3.662298,6.23383,2.066095,4.394315,2.926576,42.810458,5.126015,6.817562,4.038905,1.136693
min,39.120000,33.520000,860.91250,95.000000,36.495000,2.643750,170.377475,864.280000,858.680000,3.380000,1.720000
25%,51.460000,39.910000,862.66125,95.250000,45.405000,4.138750,179.003125,866.120000,859.590000,6.550000,1.950000
50%,55.010000,40.360000,870.86500,95.500000,45.863750,4.983750,192.751875,873.370000,865.830000,7.520000,2.040000
75%,55.380000,40.690000,873.47250,96.250000,45.955000,8.482500,223.877000,874.720000,872.090000,10.110000,2.080000
max,55.710000,43.450000,874.28625,100.000000,47.452500,9.513750,275.754750,875.130000,873.360000,14.140000,4.470000