In [1]:
import requests
import json
import uuid
from IPython.display import display_javascript, display_html, display
import pandas as pd

response = requests.get("http://api.openweathermap.org/data/2.5/forecast?id=5781004&APPID=e0c55e00bf021f6142de334823046e9e&units=imperial")
weather = response.content.decode("utf-8")
weatherDict = json.loads(weather)

In [2]:
print(json.dumps(weatherDict, indent=2))

{
  "message": 0.0104,
  "city": {
    "sys": {
      "population": 0
    },
    "coord": {
      "lon": -111.87632,
      "lat": 40.6255
    },
    "country": "US",
    "id": 5781004,
    "population": 0,
    "name": "Salt Lake County"
  },
  "cod": "200",
  "cnt": 39,
  "list": [
    {
      "weather": [
        {
          "description": "scattered clouds",
          "icon": "03n",
          "id": 802,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 3.6,
        "deg": 354
      },
      "dt_txt": "2016-11-13 03:00:00",
      "main": {
        "humidity": 100,
        "temp": 46.62,
        "temp_max": 46.62,
        "sea_level": 1036.37,
        "temp_min": 45.79,
        "grnd_level": 872.52,
        "temp_kf": 0.46,
        "pressure": 872.52
      },
      "clouds": {
        "all": 36
      },
      "dt": 1479006000
    },
    {
      "weather": [
        {
          "description": "few clouds",
          "icon": "02n",
          "id": 801,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 3.6,
        "deg": 142.5
      },
      "dt_txt": "2016-11-13 06:00:00",
      "main": {
        "humidity": 100,
        "temp": 43.47,
        "temp_max": 43.47,
        "sea_level": 1037.89,
        "temp_min": 42.92,
        "grnd_level": 872.62,
        "temp_kf": 0.3,
        "pressure": 872.62
      },
      "clouds": {
        "all": 12
      },
      "dt": 1479016800
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "02n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 5.57,
        "deg": 153.501
      },
      "dt_txt": "2016-11-13 09:00:00",
      "main": {
        "humidity": 100,
        "temp": 41.65,
        "temp_max": 41.65,
        "sea_level": 1038.44,
        "temp_min": 41.37,
        "grnd_level": 872.54,
        "temp_kf": 0.15,
        "pressure": 872.54
      },
      "clouds": {
        "all": 8
      },
      "dt": 1479027600
    },
    {
      "weather": [
        {
          "description": "broken clouds",
          "icon": "04n",
          "id": 803,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 2.04,
        "deg": 170.007
      },
      "dt_txt": "2016-11-13 12:00:00",
      "main": {
        "humidity": 100,
        "temp": 40.36,
        "temp_max": 40.36,
        "sea_level": 1040.51,
        "temp_min": 40.36,
        "grnd_level": 873.85,
        "temp_kf": 0,
        "pressure": 873.85
      },
      "clouds": {
        "all": 56
      },
      "dt": 1479038400
    },
    {
      "weather": [
        {
          "description": "scattered clouds",
          "icon": "03d",
          "id": 802,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 4.16,
        "deg": 157.501
      },
      "dt_txt": "2016-11-13 15:00:00",
      "main": {
        "humidity": 100,
        "temp": 41.42,
        "temp_max": 41.42,
        "sea_level": 1041.41,
        "temp_min": 41.42,
        "grnd_level": 874.45,
        "temp_kf": 0,
        "pressure": 874.45
      },
      "clouds": {
        "all": 44
      },
      "dt": 1479049200
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 3.74,
        "deg": 169
      },
      "dt_txt": "2016-11-13 18:00:00",
      "main": {
        "humidity": 92,
        "temp": 50.89,
        "temp_max": 50.89,
        "sea_level": 1037.8,
        "temp_min": 50.89,
        "grnd_level": 875.13,
        "temp_kf": 0,
        "pressure": 875.13
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479060000
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 3.85,
        "deg": 319.001
      },
      "dt_txt": "2016-11-13 21:00:00",
      "main": {
        "humidity": 86,
        "temp": 54.33,
        "temp_max": 54.33,
        "sea_level": 1035.77,
        "temp_min": 54.33,
        "grnd_level": 874.58,
        "temp_kf": 0,
        "pressure": 874.58
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479070800
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 2.17,
        "deg": 350.508
      },
      "dt_txt": "2016-11-14 00:00:00",
      "main": {
        "humidity": 90,
        "temp": 50.55,
        "temp_max": 50.55,
        "sea_level": 1036.24,
        "temp_min": 50.55,
        "grnd_level": 874.11,
        "temp_kf": 0,
        "pressure": 874.11
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479081600
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "02n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 2.8,
        "deg": 100.501
      },
      "dt_txt": "2016-11-14 03:00:00",
      "main": {
        "humidity": 98,
        "temp": 44.06,
        "temp_max": 44.06,
        "sea_level": 1039.22,
        "temp_min": 44.06,
        "grnd_level": 874.39,
        "temp_kf": 0,
        "pressure": 874.39
      },
      "clouds": {
        "all": 8
      },
      "dt": 1479092400
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 7.29,
        "deg": 153.504
      },
      "dt_txt": "2016-11-14 06:00:00",
      "main": {
        "humidity": 99,
        "temp": 42.56,
        "temp_max": 42.56,
        "sea_level": 1040.55,
        "temp_min": 42.56,
        "grnd_level": 874.61,
        "temp_kf": 0,
        "pressure": 874.61
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479103200
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 6.29,
        "deg": 140.501
      },
      "dt_txt": "2016-11-14 09:00:00",
      "main": {
        "humidity": 100,
        "temp": 40.75,
        "temp_max": 40.75,
        "sea_level": 1040.62,
        "temp_min": 40.75,
        "grnd_level": 874.21,
        "temp_kf": 0,
        "pressure": 874.21
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479114000
    },
    {
      "weather": [
        {
          "description": "scattered clouds",
          "icon": "03n",
          "id": 802,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 7.11,
        "deg": 138.503
      },
      "dt_txt": "2016-11-14 12:00:00",
      "main": {
        "humidity": 100,
        "temp": 39.91,
        "temp_max": 39.91,
        "sea_level": 1040.85,
        "temp_min": 39.91,
        "grnd_level": 874.17,
        "temp_kf": 0,
        "pressure": 874.17
      },
      "clouds": {
        "all": 32
      },
      "dt": 1479124800
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "02d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 7.52,
        "deg": 133.504
      },
      "dt_txt": "2016-11-14 15:00:00",
      "main": {
        "humidity": 100,
        "temp": 40.04,
        "temp_max": 40.04,
        "sea_level": 1041.43,
        "temp_min": 40.04,
        "grnd_level": 874.72,
        "temp_kf": 0,
        "pressure": 874.72
      },
      "clouds": {
        "all": 8
      },
      "dt": 1479135600
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 4.61,
        "deg": 155.001
      },
      "dt_txt": "2016-11-14 18:00:00",
      "main": {
        "humidity": 91,
        "temp": 50.36,
        "temp_max": 50.36,
        "sea_level": 1037.36,
        "temp_min": 50.36,
        "grnd_level": 874.72,
        "temp_kf": 0,
        "pressure": 874.72
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479146400
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 2.08,
        "deg": 260.003
      },
      "dt_txt": "2016-11-14 21:00:00",
      "main": {
        "humidity": 84,
        "temp": 55.01,
        "temp_max": 55.01,
        "sea_level": 1034.31,
        "temp_min": 55.01,
        "grnd_level": 873.36,
        "temp_kf": 0,
        "pressure": 873.36
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479157200
    },
    {
      "weather": [
        {
          "description": "scattered clouds",
          "icon": "03n",
          "id": 802,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 2.1,
        "deg": 309.004
      },
      "dt_txt": "2016-11-15 00:00:00",
      "main": {
        "humidity": 90,
        "temp": 51,
        "temp_max": 51,
        "sea_level": 1034.73,
        "temp_min": 51,
        "grnd_level": 873.19,
        "temp_kf": 0,
        "pressure": 873.19
      },
      "clouds": {
        "all": 32
      },
      "dt": 1479168000
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 2.1,
        "deg": 12.5017
      },
      "dt_txt": "2016-11-15 03:00:00",
      "main": {
        "humidity": 100,
        "temp": 44.23,
        "temp_max": 44.23,
        "sea_level": 1037.14,
        "temp_min": 44.23,
        "grnd_level": 873.37,
        "temp_kf": 0,
        "pressure": 873.37
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479178800
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 2.39,
        "deg": 73.5031
      },
      "dt_txt": "2016-11-15 06:00:00",
      "main": {
        "humidity": 100,
        "temp": 41.79,
        "temp_max": 41.79,
        "sea_level": 1037.9,
        "temp_min": 41.79,
        "grnd_level": 873.08,
        "temp_kf": 0,
        "pressure": 873.08
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479189600
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 2.93,
        "deg": 120.003
      },
      "dt_txt": "2016-11-15 09:00:00",
      "main": {
        "humidity": 100,
        "temp": 41.4,
        "temp_max": 41.4,
        "sea_level": 1037.11,
        "temp_min": 41.4,
        "grnd_level": 871.95,
        "temp_kf": 0,
        "pressure": 871.95
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479200400
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 3.38,
        "deg": 153.501
      },
      "dt_txt": "2016-11-15 12:00:00",
      "main": {
        "humidity": 100,
        "temp": 40.69,
        "temp_max": 40.69,
        "sea_level": 1036.27,
        "temp_min": 40.69,
        "grnd_level": 870.77,
        "temp_kf": 0,
        "pressure": 870.77
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479211200
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 3.38,
        "deg": 155.003
      },
      "dt_txt": "2016-11-15 15:00:00",
      "main": {
        "humidity": 100,
        "temp": 40.91,
        "temp_max": 40.91,
        "sea_level": 1035.31,
        "temp_min": 40.91,
        "grnd_level": 869.96,
        "temp_kf": 0,
        "pressure": 869.96
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479222000
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 3.15,
        "deg": 240.503
      },
      "dt_txt": "2016-11-15 18:00:00",
      "main": {
        "humidity": 89,
        "temp": 52.24,
        "temp_max": 52.24,
        "sea_level": 1029.98,
        "temp_min": 52.24,
        "grnd_level": 868.77,
        "temp_kf": 0,
        "pressure": 868.77
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479232800
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01d",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 1.72,
        "deg": 299.001
      },
      "dt_txt": "2016-11-15 21:00:00",
      "main": {
        "humidity": 85,
        "temp": 55.38,
        "temp_max": 55.38,
        "sea_level": 1025.49,
        "temp_min": 55.38,
        "grnd_level": 865.83,
        "temp_kf": 0,
        "pressure": 865.83
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479243600
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 1.95,
        "deg": 304.502
      },
      "dt_txt": "2016-11-16 00:00:00",
      "main": {
        "humidity": 89,
        "temp": 51.46,
        "temp_max": 51.46,
        "sea_level": 1024.77,
        "temp_min": 51.46,
        "grnd_level": 864.28,
        "temp_kf": 0,
        "pressure": 864.28
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479254400
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 4.38,
        "deg": 124
      },
      "dt_txt": "2016-11-16 03:00:00",
      "main": {
        "humidity": 93,
        "temp": 45.02,
        "temp_max": 45.02,
        "sea_level": 1025.81,
        "temp_min": 45.02,
        "grnd_level": 863.09,
        "temp_kf": 0,
        "pressure": 863.09
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479265200
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 11.23,
        "deg": 154.5
      },
      "dt_txt": "2016-11-16 06:00:00",
      "main": {
        "humidity": 99,
        "temp": 43.45,
        "temp_max": 43.45,
        "sea_level": 1025.86,
        "temp_min": 43.45,
        "grnd_level": 862.29,
        "temp_kf": 0,
        "pressure": 862.29
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479276000
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 14.14,
        "deg": 153.005
      },
      "dt_txt": "2016-11-16 09:00:00",
      "main": {
        "humidity": 95,
        "temp": 44.79,
        "temp_max": 44.79,
        "sea_level": 1024.82,
        "temp_min": 44.79,
        "grnd_level": 860.92,
        "temp_kf": 0,
        "pressure": 860.92
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479286800
    },
    {
      "weather": [
        {
          "description": "clear sky",
          "icon": "01n",
          "id": 800,
          "main": "Clear"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "wind": {
        "speed": 13.22,
        "deg": 153
      },
      "dt_txt": "2016-11-16 12:00:00",
      "main": {
        "humidity": 98,
        "temp": 43.96,
        "temp_max": 43.96,
        "sea_level": 1024.05,
        "temp_min": 43.96,
        "grnd_level": 859.79,
        "temp_kf": 0,
        "pressure": 859.79
      },
      "clouds": {
        "all": 0
      },
      "dt": 1479297600
    },
    {
      "weather": [
        {
          "description": "few clouds",
          "icon": "02d",
          "id": 801,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 13,
        "deg": 155.006
      },
      "dt_txt": "2016-11-16 15:00:00",
      "main": {
        "humidity": 97,
        "temp": 44.07,
        "temp_max": 44.07,
        "sea_level": 1022.65,
        "temp_min": 44.07,
        "grnd_level": 858.68,
        "temp_kf": 0,
        "pressure": 858.68
      },
      "clouds": {
        "all": 20
      },
      "dt": 1479308400
    },
    {
      "weather": [
        {
          "description": "few clouds",
          "icon": "02d",
          "id": 801,
          "main": "Clouds"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "wind": {
        "speed": 5.64,
        "deg": 194.001
      },
      "dt_txt": "2016-11-16 18:00:00",
      "main": {
        "humidity": 89,
        "temp": 50.16,
        "temp_max": 50.16,
        "sea_level": 1019.87,
        "temp_min": 50.16,
        "grnd_level": 858.82,
        "temp_kf": 0,
        "pressure": 858.82
      },
      "clouds": {
        "all": 12
      },
      "dt": 1479319200
    },
    {
      "weather": [
        {
          "description": "light rain",
          "icon": "10d",
          "id": 500,
          "main": "Rain"
        }
      ],
      "sys": {
        "pod": "d"
      },
      "rain": {
        "3h": 0.77
      },
      "wind": {
        "speed": 12.55,
        "deg": 304.001
      },
      "dt_txt": "2016-11-16 21:00:00",
      "main": {
        "humidity": 100,
        "temp": 44,
        "temp_max": 44,
        "sea_level": 1019.03,
        "temp_min": 44,
        "grnd_level": 859.43,
        "temp_kf": 0,
        "pressure": 859.43
      },
      "clouds": {
        "all": 92
      },
      "dt": 1479330000
    },
    {
      "weather": [
        {
          "description": "light rain",
          "icon": "10n",
          "id": 500,
          "main": "Rain"
        }
      ],
      "sys": {
        "pod": "n"
      },
      "rain": {

In [3]:
# Method for rendering collapsible JSON from: http://stackoverflow.com/questions/18873066/pretty-json-formatting-in-ipython-notebook

class RenderJSON(object):
    def __init__(self, json_data):
        if isinstance(json_data, dict):
            self.json_str = json.dumps(json_data)
        else:
            self.json_str = json
        self.uuid = str(uuid.uuid4())

    def _ipython_display_(self):
        display_html('<div id="{}" style="height: 600px; width:100%;"></div>'.format(self.uuid),
        raw=True)
        
        display_javascript("""
        require(["https://rawgit.com/caldwell/renderjson/master/renderjson.js"], function() {
        document.getElementById('%s').appendChild(renderjson(%s))
        });
        """ % (self.uuid, self.json_str), raw=True)
        
RenderJSON(weatherDict)

In [10]:
#pdWeather = pd.read_json(weatherDict)
#pdWeather

#pd.DataFrame(weatherDict["data"], columns=[x["label"] for x in weatherDict["fields"]])

timeList = []
maxTempList = []
minTempList = []
pressureList = []
tempList = []
wind_speedList = []
windDegList = []
rainList = []
rainListML = []

for weatherEntry in weatherDict["list"]:
    timeList.append(weatherEntry["dt_txt"])
    mainWeather = weatherEntry["main"]
    maxTempList.append(mainWeather["temp_max"])
    minTempList.append(mainWeather["temp_min"])
    pressureList.append(mainWeather["pressure"])
    tempList.append(mainWeather["temp"])
    windWeather = weatherEntry["wind"]
    wind_speedList.append(windWeather["speed"])
    windDegList.append(windWeather["deg"])
    if ("rain" in weatherEntry):
        rainList.append(1)
        rainListML.append(weatherEntry["rain"]["3h"])
    else:
        rainList.append(0)
        rainListML.append(0)

In [11]:
data = [('DateTime', timeList),
         ('MaxTemp', maxTempList),
         ('MinTemp', minTempList),
         ('Pressure', pressureList),
         ('Temperature', tempList),
         ('WindSpeed', wind_speedList), 
         ('WindDeg', windDegList),
         ('Rain', rainList),
         ('Rain (ml)', rainListML)
         ]
weatherForecast = pd.DataFrame.from_items(data)
weatherForecast

,DateTime,MaxTemp,MinTemp,Pressure,Temperature,WindSpeed,WindDeg,Rain,Rain (ml)
0,2016-11-13 03:00:00,46.62,45.79,872.52,46.62,3.60,354.0000,0,0.00
1,2016-11-13 06:00:00,43.47,42.92,872.62,43.47,3.60,142.5000,0,0.00
2,2016-11-13 09:00:00,41.65,41.37,872.54,41.65,5.57,153.5010,0,0.00
3,2016-11-13 12:00:00,40.36,40.36,873.85,40.36,2.04,170.0070,0,0.00
4,2016-11-13 15:00:00,41.42,41.42,874.45,41.42,4.16,157.5010,0,0.00
5,2016-11-13 18:00:00,50.89,50.89,875.13,50.89,3.74,169.0000,0,0.00
6,2016-11-13 21:00:00,54.33,54.33,874.58,54.33,3.85,319.0010,0,0.00
7,2016-11-14 00:00:00,50.55,50.55,874.11,50.55,2.17,350.5080,0,0.00
8,2016-11-14 03:00:00,44.06,44.06,874.39,44.06,2.80,100.5010,0,0.00
9,2016-11-14 06:00:00,42.56,42.56,874.61,42.56,7.29,153.5040,0,0.00
10,2016-11-14 09:00:00,40.75,40.75,874.21,40.75,6.29,140.5010,0,0.00
11,2016-11-14 12:00:00,39.91,39.91,874.17,39.91,7.11,138.5030,0,0.00
12,2016-11-14 15:00:00,40.04,40.04,874.72,40.04,7.52,133.5040,0,0.00
13,2016-11-14 18:00:00,50.36,50.36,874.72,50.36,4.61,155.0010,0,0.00
14,2016-11-14 21:00:00,55.01,55.01,873.36,55.01,2.08,260.0030,0,0.00
15,2016-11-15 00:00:00,51.00,51.00,873.19,51.00,2.10,309.0040,0,0.00
16,2016-11-15 03:00:00,44.23,44.23,873.37,44.23,2.10,12.5017,0,0.00
17,2016-11-15 06:00:00,41.79,41.79,873.08,41.79,2.39,73.5031,0,0.00
18,2016-11-15 09:00:00,41.40,41.40,871.95,41.40,2.93,120.0030,0,0.00
19,2016-11-15 12:00:00,40.69,40.69,870.77,40.69,3.38,153.5010,0,0.00
20,2016-11-15 15:00:00,40.91,40.91,869.96,40.91,3.38,155.0030,0,0.00
21,2016-11-15 18:00:00,52.24,52.24,868.77,52.24,3.15,240.5030,0,0.00
22,2016-11-15 21:00:00,55.38,55.38,865.83,55.38,1.72,299.0010,0,0.00
23,2016-11-16 00:00:00,51.46,51.46,864.28,51.46,1.95,304.5020,0,0.00
24,2016-11-16 03:00:00,45.02,45.02,863.09,45.02,4.38,124.0000,0,0.00
25,2016-11-16 06:00:00,43.45,43.45,862.29,43.45,11.23,154.5000,0,0.00
26,2016-11-16 09:00:00,44.79,44.79,860.92,44.79,14.14,153.0050,0,0.00
27,2016-11-16 12:00:00,43.96,43.96,859.79,43.96,13.22,153.0000,0,0.00
28,2016-11-16 15:00:00,44.07,44.07,858.68,44.07,13.00,155.0060,0,0.00
29,2016-11-16 18:00:00,50.16,50.16,858.82,50.16,5.64,194.0010,0,0.00
30,2016-11-16 21:00:00,44.00,44.00,859.43,44.00,12.55,304.0010,1,0.77
31,2016-11-17 00:00:00,39.00,39.00,859.59,39.00,6.55,255.5100,1,2.34
32,2016-11-17 03:00:00,39.12,39.12,860.06,39.12,10.07,264.0080,1,0.86
33,2016-11-17 06:00:00,37.15,37.15,860.78,37.15,9.35,300.0020,1,1.29
34,2016-11-17 09:00:00,36.27,36.27,861.84,36.27,7.85,303.0020,1,1.06
35,2016-11-17 12:00:00,33.52,33.52,862.85,33.52,4.47,279.0010,1,0.20
36,2016-11-17 15:00:00,34.18,34.18,864.07,34.18,9.62,262.0030,1,0.02
37,2016-11-17 18:00:00,35.70,35.70,865.98,35.70,9.84,274.0020,1,0.07
38,2016-11-17 21:00:00,37.02,37.02,866.12,37.02,10.11,268.5100,1,0.09

In [6]:
weatherForecast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
DateTime       39 non-null object
MaxTemp        39 non-null float64
MinTemp        39 non-null float64
Pressure       39 non-null float64
Temperature    39 non-null float64
WindSpeed      39 non-null float64
WindDeg        39 non-null float64
Rain           39 non-null int64
dtypes: float64(6), int64(1), object(1)
memory usage: 2.5+ KB

In [7]:
weatherForecast.describe()

,MaxTemp,MinTemp,Pressure,Temperature,WindSpeed,WindDeg,Rain
count,39.000000,39.000000,39.000000,39.000000,39.000000,39.000000,39.0
mean,43.807436,43.764872,868.345897,43.807436,5.937179,205.348918,0.0
std,5.822974,5.818249,5.994079,5.822974,3.685992,83.846970,0.0
min,33.520000,33.520000,858.680000,33.520000,1.720000,12.501700,0.0
25%,40.200000,40.200000,862.570000,40.200000,3.040000,153.002500,0.0
50%,43.450000,42.920000,870.770000,43.450000,4.470000,169.000000,0.0
75%,48.390000,47.975000,873.980000,48.390000,8.600000,276.501500,0.0
max,55.380000,55.380000,875.130000,55.380000,14.140000,354.000000,0.0