In [1]:
import requests
import json
import uuid
from IPython.display import display_javascript, display_html, display
import pandas as pd

response = requests.get("http://api.openweathermap.org/data/2.5/forecast?id=5780993&APPID=e0c55e00bf021f6142de334823046e9e&units=imperial")
weather = response.content.decode("utf-8")
weatherDict = json.loads(weather)

In [2]:
print(json.dumps(weatherDict, indent=2))

{
  "list": [
    {
      "main": {
        "humidity": 100,
        "pressure": 866.5,
        "grnd_level": 866.5,
        "temp_max": 36.45,
        "temp": 36.45,
        "sea_level": 1031.8,
        "temp_kf": 0.51,
        "temp_min": 35.53
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-17 21:00:00",
      "dt": 1479416400,
      "snow": {
        "3h": 0.234
      },
      "clouds": {
        "all": 88
      },
      "rain": {},
      "wind": {
        "deg": 317.508,
        "speed": 14.7
      },
      "weather": [
        {
          "main": "Snow",
          "id": 600,
          "icon": "13d",
          "description": "light snow"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 868.75,
        "grnd_level": 868.75,
        "temp_max": 36.21,
        "temp": 36.21,
        "sea_level": 1035.43,
        "temp_kf": 0.38,
        "temp_min": 35.52
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-18 00:00:00",
      "dt": 1479427200,
      "snow": {
        "3h": 0.09625
      },
      "clouds": {
        "all": 88
      },
      "rain": {
        "3h": 0.0075
      },
      "wind": {
        "deg": 325.5,
        "speed": 10
      },
      "weather": [
        {
          "main": "Rain",
          "id": 500,
          "icon": "10n",
          "description": "light rain"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 870.74,
        "grnd_level": 870.74,
        "temp_max": 35.17,
        "temp": 35.17,
        "sea_level": 1039.73,
        "temp_kf": 0.25,
        "temp_min": 34.72
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-18 03:00:00",
      "dt": 1479438000,
      "snow": {
        "3h": 0.05375
      },
      "clouds": {
        "all": 88
      },
      "rain": {},
      "wind": {
        "deg": 346.502,
        "speed": 5.61
      },
      "weather": [
        {
          "main": "Snow",
          "id": 600,
          "icon": "13n",
          "description": "light snow"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 872.69,
        "grnd_level": 872.69,
        "temp_max": 33.48,
        "temp": 33.48,
        "sea_level": 1043.11,
        "temp_kf": 0.13,
        "temp_min": 33.24
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-18 06:00:00",
      "dt": 1479448800,
      "snow": {
        "3h": 0.01
      },
      "clouds": {
        "all": 80
      },
      "rain": {},
      "wind": {
        "deg": 21.0059,
        "speed": 1.32
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 873.88,
        "grnd_level": 873.88,
        "temp_max": 28.78,
        "temp": 28.78,
        "sea_level": 1045.34,
        "temp_kf": 0,
        "temp_min": 28.78
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-18 09:00:00",
      "dt": 1479459600,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 145.007,
        "speed": 5.32
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 874.72,
        "grnd_level": 874.72,
        "temp_max": 26.63,
        "temp": 26.63,
        "sea_level": 1047.01,
        "temp_kf": 0,
        "temp_min": 26.63
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-18 12:00:00",
      "dt": 1479470400,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 148.001,
        "speed": 8.75
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 875.86,
        "grnd_level": 875.86,
        "temp_max": 25.04,
        "temp": 25.04,
        "sea_level": 1048.77,
        "temp_kf": 0,
        "temp_min": 25.04
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-18 15:00:00",
      "dt": 1479481200,
      "snow": {},
      "clouds": {
        "all": 8
      },
      "rain": {},
      "wind": {
        "deg": 135.003,
        "speed": 7.87
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "02d",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 876.55,
        "grnd_level": 876.55,
        "temp_max": 33.07,
        "temp": 33.07,
        "sea_level": 1045.55,
        "temp_kf": 0,
        "temp_min": 33.07
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-18 18:00:00",
      "dt": 1479492000,
      "snow": {},
      "clouds": {
        "all": 8
      },
      "rain": {},
      "wind": {
        "deg": 153.004,
        "speed": 7.27
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "02d",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 874.88,
        "grnd_level": 874.88,
        "temp_max": 36.96,
        "temp": 36.96,
        "sea_level": 1041.79,
        "temp_kf": 0,
        "temp_min": 36.96
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-18 21:00:00",
      "dt": 1479502800,
      "snow": {},
      "clouds": {
        "all": 8
      },
      "rain": {},
      "wind": {
        "deg": 140.503,
        "speed": 6.04
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "02d",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 873.51,
        "grnd_level": 873.51,
        "temp_max": 35.22,
        "temp": 35.22,
        "sea_level": 1041.34,
        "temp_kf": 0,
        "temp_min": 35.22
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-19 00:00:00",
      "dt": 1479513600,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 147.003,
        "speed": 5.84
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 872.96,
        "grnd_level": 872.96,
        "temp_max": 30.04,
        "temp": 30.04,
        "sea_level": 1042.78,
        "temp_kf": 0,
        "temp_min": 30.04
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-19 03:00:00",
      "dt": 1479524400,
      "snow": {},
      "clouds": {
        "all": 12
      },
      "rain": {},
      "wind": {
        "deg": 169.501,
        "speed": 5.21
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 801,
          "icon": "02n",
          "description": "few clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 872.6,
        "grnd_level": 872.6,
        "temp_max": 30.46,
        "temp": 30.46,
        "sea_level": 1043.11,
        "temp_kf": 0,
        "temp_min": 30.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-19 06:00:00",
      "dt": 1479535200,
      "snow": {},
      "clouds": {
        "all": 20
      },
      "rain": {},
      "wind": {
        "deg": 192.001,
        "speed": 2.71
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 801,
          "icon": "02n",
          "description": "few clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 871.76,
        "grnd_level": 871.76,
        "temp_max": 28.86,
        "temp": 28.86,
        "sea_level": 1042.52,
        "temp_kf": 0,
        "temp_min": 28.86
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-19 09:00:00",
      "dt": 1479546000,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 170.502,
        "speed": 2.86
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 870.9,
        "grnd_level": 870.9,
        "temp_max": 28.53,
        "temp": 28.53,
        "sea_level": 1041.88,
        "temp_kf": 0,
        "temp_min": 28.53
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-19 12:00:00",
      "dt": 1479556800,
      "snow": {},
      "clouds": {
        "all": 12
      },
      "rain": {},
      "wind": {
        "deg": 138.501,
        "speed": 7.05
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 801,
          "icon": "02n",
          "description": "few clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 870.94,
        "grnd_level": 870.94,
        "temp_max": 30.16,
        "temp": 30.16,
        "sea_level": 1041.6,
        "temp_kf": 0,
        "temp_min": 30.16
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-19 15:00:00",
      "dt": 1479567600,
      "snow": {},
      "clouds": {
        "all": 12
      },
      "rain": {},
      "wind": {
        "deg": 141.002,
        "speed": 7.76
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 801,
          "icon": "02d",
          "description": "few clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 870.59,
        "grnd_level": 870.59,
        "temp_max": 39.96,
        "temp": 39.96,
        "sea_level": 1036.66,
        "temp_kf": 0,
        "temp_min": 39.96
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-19 18:00:00",
      "dt": 1479578400,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 159.002,
        "speed": 5.19
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01d",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 868.73,
        "grnd_level": 868.73,
        "temp_max": 46.33,
        "temp": 46.33,
        "sea_level": 1032.35,
        "temp_kf": 0,
        "temp_min": 46.33
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-19 21:00:00",
      "dt": 1479589200,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 151.502,
        "speed": 3.65
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01d",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 867.79,
        "grnd_level": 867.79,
        "temp_max": 43.63,
        "temp": 43.63,
        "sea_level": 1032.22,
        "temp_kf": 0,
        "temp_min": 43.63
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-20 00:00:00",
      "dt": 1479600000,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 184.501,
        "speed": 4.27
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 867.99,
        "grnd_level": 867.99,
        "temp_max": 37.7,
        "temp": 37.7,
        "sea_level": 1034.27,
        "temp_kf": 0,
        "temp_min": 37.7
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-20 03:00:00",
      "dt": 1479610800,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 157,
        "speed": 4.63
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 867.67,
        "grnd_level": 867.67,
        "temp_max": 37.34,
        "temp": 37.34,
        "sea_level": 1034.84,
        "temp_kf": 0,
        "temp_min": 37.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-20 06:00:00",
      "dt": 1479621600,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 147.001,
        "speed": 7.83
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 867.29,
        "grnd_level": 867.29,
        "temp_max": 38.12,
        "temp": 38.12,
        "sea_level": 1034.81,
        "temp_kf": 0,
        "temp_min": 38.12
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-20 09:00:00",
      "dt": 1479632400,
      "snow": {},
      "clouds": {
        "all": 0
      },
      "rain": {},
      "wind": {
        "deg": 157.503,
        "speed": 9.04
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "01n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 867.11,
        "grnd_level": 867.11,
        "temp_max": 37.17,
        "temp": 37.17,
        "sea_level": 1034.74,
        "temp_kf": 0,
        "temp_min": 37.17
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-20 12:00:00",
      "dt": 1479643200,
      "snow": {},
      "clouds": {
        "all": 8
      },
      "rain": {},
      "wind": {
        "deg": 161.501,
        "speed": 6.17
      },
      "weather": [
        {
          "main": "Clear",
          "id": 800,
          "icon": "02n",
          "description": "clear sky"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 867.2,
        "grnd_level": 867.2,
        "temp_max": 37.71,
        "temp": 37.71,
        "sea_level": 1034.71,
        "temp_kf": 0,
        "temp_min": 37.71
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-20 15:00:00",
      "dt": 1479654000,
      "snow": {},
      "clouds": {
        "all": 32
      },
      "rain": {},
      "wind": {
        "deg": 159.5,
        "speed": 6.62
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 802,
          "icon": "03d",
          "description": "scattered clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 96,
        "pressure": 867.21,
        "grnd_level": 867.21,
        "temp_max": 48.93,
        "temp": 48.93,
        "sea_level": 1030.45,
        "temp_kf": 0,
        "temp_min": 48.93
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-20 18:00:00",
      "dt": 1479664800,
      "snow": {},
      "clouds": {
        "all": 24
      },
      "rain": {},
      "wind": {
        "deg": 167,
        "speed": 5.41
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 801,
          "icon": "02d",
          "description": "few clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 91,
        "pressure": 865.68,
        "grnd_level": 865.68,
        "temp_max": 51.71,
        "temp": 51.71,
        "sea_level": 1027.14,
        "temp_kf": 0,
        "temp_min": 51.71
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2016-11-20 21:00:00",
      "dt": 1479675600,
      "snow": {},
      "clouds": {
        "all": 36
      },
      "rain": {},
      "wind": {
        "deg": 187.001,
        "speed": 3.18
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 802,
          "icon": "03d",
          "description": "scattered clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 94,
        "pressure": 864.83,
        "grnd_level": 864.83,
        "temp_max": 47.29,
        "temp": 47.29,
        "sea_level": 1027.67,
        "temp_kf": 0,
        "temp_min": 47.29
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-21 00:00:00",
      "dt": 1479686400,
      "snow": {},
      "clouds": {
        "all": 68
      },
      "rain": {},
      "wind": {
        "deg": 156.003,
        "speed": 3.15
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 803,
          "icon": "04n",
          "description": "broken clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 92,
        "pressure": 864.03,
        "grnd_level": 864.03,
        "temp_max": 45.28,
        "temp": 45.28,
        "sea_level": 1028.78,
        "temp_kf": 0,
        "temp_min": 45.28
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-21 03:00:00",
      "dt": 1479697200,
      "snow": {},
      "clouds": {
        "all": 80
      },
      "rain": {},
      "wind": {
        "deg": 158.501,
        "speed": 9.75
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 803,
          "icon": "04n",
          "description": "broken clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 95,
        "pressure": 864,
        "grnd_level": 864,
        "temp_max": 46.57,
        "temp": 46.57,
        "sea_level": 1029.49,
        "temp_kf": 0,
        "temp_min": 46.57
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-21 06:00:00",
      "dt": 1479708000,
      "snow": {},
      "clouds": {
        "all": 92
      },
      "rain": {},
      "wind": {
        "deg": 173.5,
        "speed": 13.91
      },
      "weather": [
        {
          "main": "Clouds",
          "id": 804,
          "icon": "04n",
          "description": "overcast clouds"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 863.71,
        "grnd_level": 863.71,
        "temp_max": 45.71,
        "temp": 45.71,
        "sea_level": 1029.5,
        "temp_kf": 0,
        "temp_min": 45.71
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-21 09:00:00",
      "dt": 1479718800,
      "snow": {},
      "clouds": {
        "all": 68
      },
      "rain": {
        "3h": 0.0025
      },
      "wind": {
        "deg": 160.001,
        "speed": 12.62
      },
      "weather": [
        {
          "main": "Rain",
          "id": 500,
          "icon": "10n",
          "description": "light rain"
        }
      ]
    },
    {
      "main": {
        "humidity": 100,
        "pressure": 863.38,
        "grnd_level": 863.38,
        "temp_max": 44.06,
        "temp": 44.06,
        "sea_level": 1029.19,
        "temp_kf": 0,
        "temp_min": 44.06
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2016-11-21 12:00:00",
      "dt": 1479729600,
      "snow": {},
      "clouds": {
        "all": 92
      },
      "rain": {
        "3h": 0.04
      },
      "wind": {
        "deg": 188.503,
        "speed": 8.34
      },
      "weather": [
        {

In [3]:
# Method for rendering collapsible JSON from: http://stackoverflow.com/questions/18873066/pretty-json-formatting-in-ipython-notebook

class RenderJSON(object):
    def __init__(self, json_data):
        if isinstance(json_data, dict):
            self.json_str = json.dumps(json_data)
        else:
            self.json_str = json
        self.uuid = str(uuid.uuid4())

    def _ipython_display_(self):
        display_html('<div id="{}" style="height: 600px; width:100%;"></div>'.format(self.uuid),
        raw=True)
        
        display_javascript("""
        require(["https://rawgit.com/caldwell/renderjson/master/renderjson.js"], function() {
        document.getElementById('%s').appendChild(renderjson(%s))
        });
        """ % (self.uuid, self.json_str), raw=True)
        
RenderJSON(weatherDict)

In [4]:
#pdWeather = pd.read_json(weatherDict)
#pdWeather

#pd.DataFrame(weatherDict["data"], columns=[x["label"] for x in weatherDict["fields"]])

timeList = []
maxTempList = []
minTempList = []
pressureList = []
humidityList = []
tempList = []
wind_speedList = []
windDegList = []
rainList = []
rainListMM = []
snowList = []
snowListMM = []

for weatherEntry in weatherDict["list"]:
    timeList.append(weatherEntry["dt_txt"])
    mainWeather = weatherEntry["main"]
    maxTempList.append(mainWeather["temp_max"])
    minTempList.append(mainWeather["temp_min"])
    pressureList.append(mainWeather["pressure"])
    humidityList.append(mainWeather["humidity"])
    tempList.append(mainWeather["temp"])
    windWeather = weatherEntry["wind"]
    wind_speedList.append(windWeather["speed"])
    windDegList.append(windWeather["deg"])
    if "3h" in weatherEntry["rain"]:
        rainList.append(1)
        rainListMM.append(weatherEntry["rain"]["3h"])
    else:
        rainList.append(0)
        rainListMM.append(0)
    if "3h" in weatherEntry["snow"]:
        snowList.append(1)
        snowListMM.append(weatherEntry["snow"]["3h"])
    else:
        snowList.append(0)
        snowListMM.append(0)

In [5]:
data = [('DateTime', timeList),
         ('MaxTemp', maxTempList),
         ('MinTemp', minTempList),
         ('Pressure', pressureList),
         ('Humidity', humidityList),
         ('Temperature', tempList),
         ('WindSpeed', wind_speedList), 
         ('WindDeg', windDegList),
         ('Rain', rainList),
         ('Rain (mm)', rainListMM),
         ('Snow', snowList),
         ('Snow (mm)', snowListMM)
         ]

weatherForecast = pd.DataFrame.from_items(data)
weatherForecast["DateTime"] = weatherForecast["DateTime"].apply(lambda x: str(x)[:10])

finalForecast = weatherForecast.groupby("DateTime").mean()

finalForecast["MinTemp"] = weatherForecast.groupby("DateTime").min()["MinTemp"]
finalForecast["MaxTemp"] = weatherForecast.groupby("DateTime").max()["MaxTemp"]
finalForecast["MaxPressure"] = weatherForecast.groupby("DateTime").max()["Pressure"]
finalForecast["MinPressure"] = weatherForecast.groupby("DateTime").min()["Pressure"]
finalForecast["MaxWindSpeed"] = weatherForecast.groupby("DateTime").max()["WindSpeed"]
finalForecast["MinWindSpeed"] = weatherForecast.groupby("DateTime").min()["WindSpeed"]

finalForecast

,MaxTemp,MinTemp,Pressure,Humidity,Temperature,WindSpeed,WindDeg,Rain,Rain (mm),Snow,Snow (mm),MaxPressure,MinPressure,MaxWindSpeed,MinWindSpeed
DateTime,,,,,,,,,,,,,,,
2016-11-17,36.45,35.53,866.50000,100.000,36.450000,14.700000,317.508000,0.000,0.000000,1.000,0.234,866.50,866.50,14.70,14.70
2016-11-18,36.96,25.04,873.50875,100.000,31.917500,6.522500,176.815737,0.125,0.000937,0.375,0.020,876.55,868.75,10.00,1.32
2016-11-19,46.33,28.53,871.49875,100.000,33.695000,5.033750,158.626750,0.000,0.000000,0.000,0.000,873.51,868.73,7.76,2.71
2016-11-20,51.71,37.17,867.24250,98.375,41.538750,5.893750,165.125875,0.000,0.000000,0.000,0.000,867.99,865.68,9.04,3.18
2016-11-21,47.29,42.00,863.51875,97.625,45.122500,7.982500,178.938963,0.625,0.239062,0.000,0.000,864.83,862.33,13.91,2.17
2016-11-22,41.82,39.12,868.72000,100.000,40.125714,5.505714,287.215286,1.000,0.464286,0.000,0.000,873.80,863.60,7.83,2.89

In [6]:
finalForecast.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 2016-11-17 to 2016-11-22
Data columns (total 15 columns):
MaxTemp         6 non-null float64
MinTemp         6 non-null float64
Pressure        6 non-null float64
Humidity        6 non-null float64
Temperature     6 non-null float64
WindSpeed       6 non-null float64
WindDeg         6 non-null float64
Rain            6 non-null float64
Rain (mm)       6 non-null float64
Snow            6 non-null float64
Snow (mm)       6 non-null float64
MaxPressure     6 non-null float64
MinPressure     6 non-null float64
MaxWindSpeed    6 non-null float64
MinWindSpeed    6 non-null float64
dtypes: float64(15)
memory usage: 768.0+ bytes

In [7]:
finalForecast.describe()

,MaxTemp,MinTemp,Pressure,Humidity,Temperature,WindSpeed,WindDeg,Rain,Rain (mm),Snow,Snow (mm),MaxPressure,MinPressure,MaxWindSpeed,MinWindSpeed
count,6.000000,6.00000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,43.426667,34.56500,868.498125,99.333333,38.141577,7.606369,214.038435,0.291667,0.117381,0.229167,0.042333,870.530000,865.931667,10.540000,4.495000
std,6.083442,6.49448,3.592287,1.059678,5.011656,3.622155,69.485535,0.423281,0.194958,0.406330,0.094237,4.711607,2.629399,3.042256,5.042217
min,36.450000,25.04000,863.518750,97.625000,31.917500,5.033750,158.626750,0.000000,0.000000,0.000000,0.000000,864.830000,862.330000,7.760000,1.320000
25%,38.175000,30.28000,866.685625,98.781250,34.383750,5.602723,168.048341,0.000000,0.000000,0.000000,0.000000,866.872500,864.120000,8.132500,2.305000
50%,44.075000,36.35000,867.981250,100.000000,38.287857,6.208125,177.877350,0.062500,0.000469,0.000000,0.000000,870.750000,866.090000,9.520000,2.800000
75%,47.050000,38.63250,870.804063,100.000000,41.185491,7.617500,260.146205,0.500000,0.179531,0.281250,0.015000,873.727500,868.172500,12.932500,3.107500
max,51.710000,42.00000,873.508750,100.000000,45.122500,14.700000,317.508000,1.000000,0.464286,1.000000,0.234000,876.550000,868.750000,14.700000,14.700000