In [ ]:
# Salt Lake City AQI Predictions and Forecasting

*Basic Info:*                                                                      

Title: Salt Lake City AQI Predictions and Forecasting.                                                 

Team Members:                                                         
+ Michael Northrup, u0992000,  michael.northrup@yahoo.com
+ Grant (Rob) Olsen, u0684253, rolsenrob@gmail.com
+ Dzevad Fitozovic, u0191522, dfitozovic@hotmail.com

## Background and Motivation.

We think that the quality of our air here in the valley is often a topic of discussion. However, the primary motivation came from one of our assignments. There we attempted to use the AQI to give us a moving average in order to be able to issue a warning to sensitive groups when an upwards trend was most likely occurring. We wanted to improve and expand on that, so in this project we want to see if we can predict the AQI for a few days in advance, creating a forecast for up to a week in advance. We also wish to see if we can make an AQI long term forecast model, so that one would be able to see how many days of poor air quality we can expect to see as our valley population rises. We do not have a background nor have we done any research in the area, but it seemed like an interesting problem.

## Project Objectives.

Our primary objective is to devise a model to obtain an AQI forecast much like we have a weather forecast.  Additionally, we would like to know how population growth in the valley will be affecting the number of days the AQI will reach over 101, therefore creating a forecast for future years based primarily on population growth. Population growth seems like a good measure for the increasing days of unhealthy air since it drives the amount of energy used, for example from heating and air conditioning of homes and cars on the roads in the valley. On the other hand short term AQI data combined with weather forecasts should be useful in creating a short term forecast model. A short term model can be useful in warning sensitive groups of upcoming poor air quality days. And, if we can create a good predictive long term model, then it can be used as supporting evidence for a need to make a valley wide plan for future energy consumption that could limit the amount of pollutants like PM2.5 which accumulate due to our natural inversion conditions.

## Data.

We will need to gather and clean a significant amount of data from several sources. For the long term
projection model the air quality data will be collected from https://www.epa.gov/outdoor-air-qualitydata.
However, each year comes as a separate data-file, so it will need to be cleaned and combined.
To calculate projections for population growth we already obtained Salt Lake Valley census data from
http://www.census.gov/popest/data/index.html, and followed links to obtain historical data for years after 2010. Data formats from this source varied since the most recent years use newer data formats. Therefore, much of this data was formated and cleaned outside of the notebook. For our short term forecasting we will need an accurate 1-5 day weather forecast for the valley and previous days AQI, which we'll obtain by either web scraping http://www.weather.gov/ or more likely the API from http://openweathermap.org/. However, we may need further data sources as we continue to process the data from these sites. Some preliminary data analysis, formatting and cleanup was included in this
proposal.

In [3]:
# imports
import pandas as pd
import matplotlib.pyplot as plt 
%pylab inline
%matplotlib inline  
plt.rcParams['figure.figsize'] = (14, 8)

Populating the interactive namespace from numpy and matplotlib

## Data Processing.

Most of the cleanup for the population data and short term climate data was completed in OpenOffice out of convenience. Data clean up in the long term model air quality data set is expected to be comparable to the cleanup in Homework #3, although there is a lot more data which needed to be cleaned and combined. Also, we saw even more complexity in data cleanup of the population growth data and we expect substantial data cleanup in use of the API for the most recent weather forecasts. We expect that we should be able to give a fairly accurate short term AQI prediction, namely what type of air quality day one expects to have in the upcoming days, and long term projections based on population growth of at least 1-5 years in advance, assuming a reasonable amount of uncertainty and that current trends continue indefinitely.

In [4]:
#load climate data from 1999-Nov 7th 2016 (Come up with solution to up to date issue)
all_weather_data = pd.DataFrame()

weather_data_1999 = pd.read_csv("1999.csv",parse_dates=True)
df1999 = pd.DataFrame(weather_data_1999).groupby("Date").max()

weather_data_2000 = pd.read_csv("2000.csv",parse_dates=True)
df2000 = pd.DataFrame(weather_data_2000).groupby("Date").max()

weather_data_2001 = pd.read_csv("2001.csv",parse_dates=True)
df2001 = pd.DataFrame(weather_data_2001).groupby("Date").max()

weather_data_2002 = pd.read_csv("2002.csv",parse_dates=True)
df2002 = pd.DataFrame(weather_data_2002).groupby("Date").max()

weather_data_2003 = pd.read_csv("2003.csv",parse_dates=True)
df2003 = pd.DataFrame(weather_data_2003).groupby("Date").max()

weather_data_2004 = pd.read_csv("2004.csv",parse_dates=True)
df2004 = pd.DataFrame(weather_data_2004).groupby("Date").max()

weather_data_2005 = pd.read_csv("2005.csv",parse_dates=True)
df2005 = pd.DataFrame(weather_data_2005).groupby("Date").max()

weather_data_2006 = pd.read_csv("2006.csv",parse_dates=True)
df2006 = pd.DataFrame(weather_data_2006).groupby("Date").max()

weather_data_2007 = pd.read_csv("2007.csv",parse_dates=True)
df2007 = pd.DataFrame(weather_data_2007).groupby("Date").max()

weather_data_2008 = pd.read_csv("2008.csv",parse_dates=True)
df2008 = pd.DataFrame(weather_data_2008).groupby("Date").max()

weather_data_2009 = pd.read_csv("2009.csv",parse_dates=True)
df2009 = pd.DataFrame(weather_data_2009).groupby("Date").max()

weather_data_2010 = pd.read_csv("2010.csv",parse_dates=True)
df2010 = pd.DataFrame(weather_data_2010).groupby("Date").max()

weather_data_2011 = pd.read_csv("2011.csv",parse_dates=True)
df2011 = pd.DataFrame(weather_data_2011).groupby("Date").max()

weather_data_2012 = pd.read_csv("2012.csv",parse_dates=True)
df2012 = pd.DataFrame(weather_data_2012).groupby("Date").max()

weather_data_2013 = pd.read_csv("2013.csv",parse_dates=True)
df2013 = pd.DataFrame(weather_data_2013).groupby("Date").max()

weather_data_2014 = pd.read_csv("2014.csv",parse_dates=True)
df2014 = pd.DataFrame(weather_data_2014).groupby("Date").max()

weather_data_2015 = pd.read_csv("2015.csv",parse_dates=True)
df2015 = pd.DataFrame(weather_data_2015).groupby("Date").max()

weather_data_2016 = pd.read_csv("2016.csv",parse_dates=True)
df2016 = pd.DataFrame(weather_data_2016).groupby("Date").max()

weather_data_present = pd.read_excel("2016.csv",parse_dates=True)
dfpresent = pd.DataFrame(weather_data_present)


all_weather_data = df1999.append(df2000)
all_weather_data = all_weather_data.append(df2001)
all_weather_data = all_weather_data.append(df2002)
all_weather_data = all_weather_data.append(df2003)
all_weather_data = all_weather_data.append(df2004)
all_weather_data = all_weather_data.append(df2005)
all_weather_data = all_weather_data.append(df2006)
all_weather_data = all_weather_data.append(df2007)
all_weather_data = all_weather_data.append(df2008)
all_weather_data = all_weather_data.append(df2009)
all_weather_data = all_weather_data.append(df2010)
all_weather_data = all_weather_data.append(df2011)
all_weather_data = all_weather_data.append(df2012)
all_weather_data = all_weather_data.append(df2013)
all_weather_data = all_weather_data.append(df2014)
all_weather_data = all_weather_data.append(df2015)
all_weather_data = all_weather_data.append(df2016)

del all_weather_data['AQS_SITE_ID']
del all_weather_data['POC']
del all_weather_data['DAILY_OBS_COUNT']
del all_weather_data['AQS_PARAMETER_CODE']
del all_weather_data['AQS_PARAMETER_DESC']
del all_weather_data['PERCENT_COMPLETE']
del all_weather_data['CBSA_NAME']
del all_weather_data['STATE_CODE']
del all_weather_data['CBSA_CODE']
del all_weather_data['STATE']
del all_weather_data['COUNTY_CODE']
del all_weather_data['UNITS']
del all_weather_data['SITE_LATITUDE']
del all_weather_data['SITE_LONGITUDE']
del all_weather_data['COUNTY']
del all_weather_data['Daily Mean PM2.5 Concentration']


all_weather_data = all_weather_data.append(dfpresent)

idx = pd.date_range('01-01-1999', '09-30-2016')
all_weather_data.index = pd.DatetimeIndex(all_weather_data.index)
all_weather_data = all_weather_data.reindex(idx,method='ffill')
all_weather_data["14d"] = np.round(all_weather_data["DAILY_AQI_VALUE"].rolling(window = 14, center = False).mean(), 2)
all_weather_data["7d"] = np.round(all_weather_data["DAILY_AQI_VALUE"].rolling(window = 7, center = False).mean(), 2)
all_weather_data["3d"] = np.round(all_weather_data["DAILY_AQI_VALUE"].rolling(window = 3, center = False).mean(), 2)

In [5]:
all_weather_data.tail()

            DAILY_AQI_VALUE    14d     7d     3d
2016-09-26               33  25.86  24.57  23.00
2016-09-27               45  26.71  26.00  32.67
2016-09-28               43  28.36  27.71  40.33
2016-09-29               20  27.71  28.14  36.00
2016-09-30               15  26.21  27.43  26.00

In [18]:
# load climate data from Oct. 1st to Oct. 26th for use in short term forecasting. 
Oct_weather_data_slv = pd.read_csv("recent_climate_data.txt")
# create weather symbols list from original october climate data 
weather_symbols = pd.Series(['FOG OR MIST', 'FOG REDUCING VISIBILITY TO 1/4 MILE OR LESS', 'THUNDER', 'ICE PELLETS', 'HAIL',
                            'FREEZING RAIN OR DRIZZLE', 'DUSTSTORM OR SANDSTORM: VSBY 1/2 MILE OR LESS', 'SMOKE OR HAZE',
                            'BLOWING SNOW','TORNADO'],
                             name="Weather Type",
                             index=["1", "2", "3", "4", "5", "6", "7", "8", "9", "X"])
# reindex by day of month. 
Oct_weather_data_slv = Oct_weather_data_slv.set_index(['Day of month'])
#Oct_weather_data_slv = Oct_weather_data_slv.drop(['Day of month'], axis = 0)
print(weather_symbols)
Oct_weather_data_slv.info()
Oct_weather_data_slv.head()

1                                      FOG OR MIST
2      FOG REDUCING VISIBILITY TO 1/4 MILE OR LESS
3                                          THUNDER
4                                      ICE PELLETS
5                                             HAIL
6                         FREEZING RAIN OR DRIZZLE
7    DUSTSTORM OR SANDSTORM: VSBY 1/2 MILE OR LESS
8                                    SMOKE OR HAZE
9                                     BLOWING SNOW
X                                          TORNADO
Name: Weather Type, dtype: object
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26 entries, 1 to 26
Data columns (total 18 columns):
MAX Temp (F)            26 non-null int64
MIN Temp (F)            26 non-null int64
AVG Temp (F)            26 non-null int64
DEP                     26 non-null int64
HDD                     26 non-null int64
CDD                     26 non-null int64
Percipitation (inch)    26 non-null object
Snow                    26 non-null object
12ZDPTH                 26 non-null int64
Avg wind speed (mph)    26 non-null float64
Max wind speed (mph)    26 non-null int64
2minDIR                 26 non-null int64
MIN                     26 non-null object
PSBL                    26 non-null object
Weather type            26 non-null int64
WX                      10 non-null float64
Peak wind speed         26 non-null int64
Wind direction (deg)    26 non-null int64
dtypes: float64(2), int64(12), object(4)
memory usage: 3.9+ KB

,MAX Temp (F),MIN Temp (F),AVG Temp (F),DEP,HDD,CDD,Percipitation (inch),Snow,12ZDPTH,Avg wind speed (mph),Max wind speed (mph),2minDIR,MIN,PSBL,Weather type,WX,Peak wind speed,Wind direction (deg)
Day of month,,,,,,,,,,,,,,,,,,
1,81,58,70,11,0,5,T,0.0,0,11.8,26,170,M,M,3,3.0,33,160
2,81,55,68,9,0,3,0.01,0.0,0,13.5,32,190,M,M,7,3.0,49,210
3,66,46,56,-2,9,0,T,0.0,0,14.0,31,260,M,M,6,3.0,42,260
4,60,41,51,-7,14,0,0.00,0.0,0,7.4,14,320,M,M,4,NaN,19,360
5,58,41,50,-7,15,0,0.10,0.0,0,7.3,28,290,M,M,7,3.0,35,280

In [ ]:
# load salt lake county population data for years 1990 through 2015
sl_county_1990to2015 = pd.read_csv("popEstimate_SL_county_1990-2015.csv")
sl_county_1990to2015.info()
sl_county_1990to2015

## Exploratory Analysis.

We will plot population VS. number of days AQI is over 101 and apply regression analysis and extrapolation on this data. We will also attempt to visualize how precipitation, temperature and wind speed effect the short term prediction model.

## Analysis Methodology.

For our short term model, we will combine the weather predictions and past month data to create a forecast model for up to a week in advance. On the other hand, for the long term model we will see how well population growth is correlated with past  past population data and AQI than project for years to come. Additionally, we will expand the model by including past climate information to normalize for drier than average years.

## Project Schedule.

We plan on mostly working together to achieve each project deadline. However, some work will need to be divided out if we are unable to reach each week's objective during team meetings. 

By Friday 11-04-16
+ Obtain and format long term climate, population and AQI data. (Rob, Michael and Dzevad)
+ Obtain and format short term climate and AQI data. (Rob, Michael and Dzevad)
+ Obtain current weather forecast using an API. (Rob, Michael and Dzevad)

By Friday 11-11-16 
+ Create a long term forecasting model and test it on year 2015. (Rob, Michael and Dzevad) 
+ Create a short term forecasting model and check if it is able to predict a few days ahead. (Rob, Michael and Dzevad) 

By Friday 11-18-16
+ Tested the short term and long term model. (Rob, Michael and Dzevad)
+ Created plots to help visualize the data. (Rob, Michael and Dzevad)
+ Turn in project milestone. (Rob, Michael and Dzevad)

By Wednesday 11-23-16 
+ Refine the short term and long term model. (Rob, Michael and Dzevad)
+ Begin creating Project Screen-Cast. (Rob, Michael and Dzevad)
+ Begin creating presentation. (Rob, Michael and Dzevad)

By Friday 12-02-16
+ Completed AQI perdition and forecasting project notebook. (Rob, Michael and Dzevad)
+ Completed Project Screen-Cast and presentation. (Rob, Michael and Dzevad)